// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from 'sonner';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase environment variables. Please check your .env file.");
  toast.error("Cloud connection not configured. Some features may be limited.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});

/**
 * Standardized wrapper for Supabase Edge Functions with robust error handling
 */
export async function safeInvoke<T = unknown>(
  functionName: string,
  options?: {
    body?: Record<string, unknown>;
    method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
    headers?: Record<string, string>;
    showErrorToast?: boolean;
  }
): Promise<{ data: T | null; error: Error | null }> {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const error = new Error("Supabase is not correctly configured. Please check your system settings.");
    console.error("[Supabase safeInvoke Error] Configuration missing:", error);
    if (options?.showErrorToast !== false) {
      toast.error(error.message);
    }
    return { data: null, error };
  }

  try {
    const { showErrorToast = true, ...invokeOptions } = options || {};

    let finalUrl = functionName;
    const finalOptions = { ...invokeOptions };

    // Handle GET params from body for convenience
    if (invokeOptions.method === 'GET' && invokeOptions.body) {
      const params = new URLSearchParams();
      Object.entries(invokeOptions.body).forEach(([key, value]) => {
        params.append(key, String(value));
      });
      const queryString = params.toString();
      if (queryString) {
        finalUrl = `${functionName}?${queryString}`;
      }
      // Remove body from GET request
      delete finalOptions.body;
    }

    // Log diagnostic information before invoking
    console.log(`[Supabase safeInvoke] Invoking function: ${finalUrl}`);
    console.log(`[Supabase safeInvoke] Options:`, JSON.stringify(finalOptions, null, 2));

    // Check current session
    const { data: sessionData } = await supabase.auth.getSession();
    console.log(`[Supabase safeInvoke] Session exists:`, !!sessionData.session);
    console.log(`[Supabase safeInvoke] Session expires at:`, sessionData.session?.expires_at);
    console.log(`[Supabase safeInvoke] User ID:`, sessionData.session?.user?.id);

    const { data, error } = await supabase.functions.invoke(finalUrl, finalOptions);

    if (error) {
      // Force suppress for background services like embeddings to avoid console spam
      const shouldSuppress = !showErrorToast || functionName === 'get-embeddings';

      if (shouldSuppress) {
        // Use console.debug so it doesn't show up as an error/warning in the console
        console.debug(`[Supabase Function Error] ${functionName} (suppressed):`, error);
      } else {
        console.error(`[Supabase Function Error] ${functionName}:`, error);
        if ('context' in error) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          console.error(`[Supabase Function Error Context]`, (error as any).context);
        }
      }

      if (error instanceof Error) {
        const errorMsg = error.message.toLowerCase();

        // Check for 401 Unauthorized specifically
        if (errorMsg.includes('401') || errorMsg.includes('unauthorized') || errorMsg.includes('auth')) {
          console.warn(`[Supabase 401] Authentication failed for function "${functionName}". Session may be expired or invalid.`);
          if (showErrorToast) {
            toast.error("Session expired or unauthorized. Please sign in again to continue.");
          }
          return { data: null, error: new Error("UNAUTHORIZED") };
        }

        if (errorMsg.includes('cors')) {
          if (showErrorToast) toast.error("Network restriction (CORS) prevented service access.");
        } else if (errorMsg.includes('jwt') || errorMsg.includes('token')) {
          if (showErrorToast) toast.error("Session expired. Please sign in again.");
        } else {
          // Check for 500 errors specifically to guide the user
          if (errorMsg.includes('500') || errorMsg.includes('non-2xx')) {
            console.warn(`[Supabase 500 Warning] Function "${functionName}" returned a server error. This often means a secret (like OPENAI_API_KEY) is missing or an API quota was hit. Check Supabase function logs.`);
          }
          if (showErrorToast) {
            toast.error(`Service Error: ${error.message}`);
          }
        }
        return { data: null, error };
      }

      return { data: null, error: new Error(String(error)) };
    }

    return { data, error: null };
  } catch (err) {
    console.error(`[Supabase Function Exception] ${functionName}:`, err);
    const error = err instanceof Error ? err : new Error(String(err));
    const { showErrorToast = true } = options || {};

    if (showErrorToast) {
      toast.error("A network or system error occurred.");
    }
    return { data: null, error };
  }
}