// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from 'sonner';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase environment variables. Please check your .env file.");
  toast.error("Cloud connection not configured. Some features may be limited.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Standardized wrapper for Supabase Edge Functions with robust error handling
 */
export async function safeInvoke<T = unknown>(
  functionName: string,
  options?: {
    body?: Record<string, unknown>;
    method?: 'GET' | 'POST' | 'PUT' | 'DELETE';
    headers?: Record<string, string>;
    showErrorToast?: boolean;
  }
): Promise<{ data: T | null; error: Error | null }> {
  try {
    const { showErrorToast = true, ...invokeOptions } = options || {};
    const { data, error } = await supabase.functions.invoke(functionName, invokeOptions);

    if (error) {
      // Force suppress for background services like embeddings to avoid console spam
      const shouldSuppress = !showErrorToast || functionName === 'get-embeddings';

      if (shouldSuppress) {
        // Use console.debug so it doesn't show up as an error/warning in the console
        console.debug(`[Supabase Function Error] ${functionName} (suppressed):`, error);
      } else {
        console.error(`[Supabase Function Error] ${functionName}:`, error);
        if ('context' in error) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          console.error(`[Supabase Function Error Context]`, (error as any).context);
        }
      }

      if (error instanceof Error) {
        if (error.message.includes('CORS')) {
          if (showErrorToast) toast.error("Network restriction (CORS) prevented service access.");
        } else if (error.message.includes('JWT')) {
          if (showErrorToast) toast.error("Session expired. Please sign in again.");
        } else {
          // Check for 500 errors specifically to guide the user
          if (error.message.includes('500') || error.message.includes('non-2xx')) {
            console.warn(`[Supabase 500 Warning] Function "${functionName}" returned a server error. This often means a secret (like OPENAI_API_KEY) is missing or an API quota was hit. Check Supabase function logs.`);
          }
          if (showErrorToast) {
            toast.error(`Service Error: ${error.message}`);
          }
        }
        return { data: null, error };
      }

      return { data: null, error: new Error(String(error)) };
    }

    return { data, error: null };
  } catch (err) {
    console.error(`[Supabase Function Exception] ${functionName}:`, err);
    const error = err instanceof Error ? err : new Error(String(err));
    const { showErrorToast = true } = options || {};

    if (showErrorToast) {
      toast.error("A network or system error occurred.");
    }
    return { data: null, error };
  }
}